### ISSUE TITLE
Issue with TypeScript declarations in 'sakana-react' library in newer versions of TypeScript

### ISSUE THREAD

**Issue by Skyline-9** [boiboif/sakana-react#1]
I encountered an issue using newer versions of Typescript:

> There are types at 'node_modules/sakana-react/dist/sakana-react.d.ts', but this result could not be resolved when respecting package.json "exports". The 'sakana-react' library may need to update its package.json or typings.

The `typing` field in `package.json` is no longer used if there is an `exports` field: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#packagejson-exports-imports-and-self-referencing

Solution is to add types in export

Example: https://stackoverflow.com/questions/76211877/the-xxxx-library-may-need-to-update-its-package-json-or-typings-ts

**Comment by boiboif** [comment]
Should be fixed in v1.2.0
